# Generated by Django 4.2.7 on 2026-04-16 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('health', '💪 Health & Fitness'), ('mind', '🧠 Mind & Learning'), ('productivity', '⚡ Productivity'), ('social', '🤝 Social'), ('creativity', '🎨 Creativity'), ('wellness', '🧘 Wellness'), ('finance', '💰 Finance'), ('other', '✨ Other')], default='other', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('color', models.CharField(choices=[('#FF6B6B', 'Coral Red'), ('#4ECDC4', 'Teal'), ('#45B7D1', 'Sky Blue'), ('#96CEB4', 'Sage Green'), ('#FFEAA7', 'Sunny Yellow'), ('#DDA0DD', 'Plum'), ('#98D8C8', 'Mint'), ('#F7DC6F', 'Gold'), ('#BB8FCE', 'Lavender'), ('#F0B27A', 'Peach'), ('#82E0AA', 'Emerald'), ('#85C1E9', 'Light Blue')], default='#4ECDC4', max_length=7)),
                ('target_count', models.PositiveIntegerField(default=1, help_text='How many times per period')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_color', models.CharField(default='#4ECDC4', max_length=7)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
