# Generated by Django 4.2.7 on 2026-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health & Fitness'), ('mind', 'Mind & Learning'), ('productivity', 'Productivity'), ('social', 'Social'), ('creativity', 'Creativity'), ('wellness', 'Wellness'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
